development:
  adapter: postgresql
  database: db1
  username: uid
  password: pwd
  host: localhost

test:
  adapter: postgresql
  database: db1
  username: uid
  password: pwd
  host: localhost

production:
  adapter: postgresql
  database: db1
  username: uid
  password: pwd
  host: localhost
