development:
  adapter: mysql
  database: esquare6_db1
  username: esquare6_echung
  password: esec28a
  host: localhost

test:
  adapter: mysql
  database: esquare6_db1
  username: esquare6_echung
  password: esec28a
  host: localhost

production:
  adapter: mysql
  database: esquare6_db1
  username: esquare6_echung
  password: esec28a
  host: localhost
